CAM:
  NAME: "CAM_18"
  NUMBER_MOI: 2
  ROI_DEFAULT: [[131, 307], [605, 148], [941, 249], [885, 691]]
  TRACKING_ROI: [[30, 307], [605, 80], [975, 226],[885, 719], [700, 719]]
  # MOI1: [[549, 144], [297, 505]]
  # MOI2: [[925, 487], [715, 144]]
  LINE1: [[207, 278], [462, 412]]
  LINE2: [[761, 203], [941, 256]]